[cr146] Fix intermittent deps issue when including `sidebar_item.h`
The issue was only seeming to occur on Mac. Fixed by moving buildflgas deps to
public_deps since they are included from public headers.

    17:49:31  In file included from ../../brave/browser/ui/views/frame/layout/brave_browser_view_tabbed_layout_impl.cc:16:
    17:49:31  In file included from ../../brave/browser/ui/views/sidebar/sidebar_container_view.h:14:
    17:49:31  In file included from ../../brave/browser/ui/sidebar/sidebar.h:9:
    17:49:31  In file included from ../../brave/components/sidebar/browser/sidebar_service.h:17:
    17:49:31
     ../../brave/components/sidebar/browser/sidebar_item.h:10:10: fatal error: 'brave/components/brave_talk/buildflags/buildflags.h' file not found
    17:49:31     10 | #include "brave/components/brave_talk/buildflags/buildflags.h"
    17:49:31        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    17:49:31  1 error generated.